# Generated by Django 5.2.3 on 2025-07-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', help_text='A longer description for the task', max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(help_text='When the task is due', verbose_name='Due date/time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(help_text='The task status', on_delete=django.db.models.deletion.RESTRICT, to='simple_api_app.status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Title for the task', max_length=32),
        ),
    ]
